# Generated by Django 5.0.6 on 2024-05-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_ip', models.CharField(max_length=50, verbose_name='IP адрес')),
                ('time', models.DateTimeField(verbose_name='Дата записи лога')),
                ('remote_user', models.CharField(max_length=50, verbose_name='Пользователь')),
                ('request_method', models.CharField(max_length=10, verbose_name='Метод запроса')),
                ('request_url', models.CharField(max_length=10, verbose_name='URL запроса')),
                ('response', models.IntegerField(verbose_name='Статус запроса')),
                ('bytes_response', models.IntegerField(verbose_name='Размер запроса')),
                ('referrer', models.CharField(max_length=50, verbose_name='URL запроса')),
                ('agent', models.CharField(max_length=200, verbose_name='URL запроса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'ordering': ['-time'],
            },
        ),
    ]
